---
title: "figure1"
author: "GG"
date: "2024-10-29"
output: html_document
---

```{r, echo=FALSE,message=FALSE,results='hide',warning=FALSE}
#Load libraries
library(tidyverse)
library(vegan)
library(ape)
library(llnl)
library(ggpubr)
library(pairwiseAdonis)
library(patchwork)
library(cowplot)
library(rstatix)
library(ComplexUpset)
```

#Load functions
```{r functions, echo=FALSE}
alpha.div.plot <- function(df,stats.df,x,y,fill,color,xlab,ylab,legend.title,
                           text.size,
                            box.alpha = 0,
                            box.line.size = 0.6,
                            box.outliers = FALSE, jitter.width = 0.15,
                            dodge.width = 0.9,jitter.height = 0,
                            jitter.alpha = 0.7,jitter.size = 2,rotate = 0,
                            hide.ns = TRUE, stat.size = 6,
                            stat.step = 0.1, stat.tip = 0,stat.backet.nudge = 0,
                           legend = "none"
                            ){
  ggboxplot(df,x=x,y=y,fill=fill,color=fill,
            outliers = box.outliers,alpha = box.alpha,
            size = box.line.size)+
  geom_jitter(position = position_jitterdodge(jitter.width = jitter.width, dodge.width = dodge.width ,jitter.height = jitter.height),
              alpha = jitter.alpha,
              size = jitter.size,
              aes(color = !!sym(fill)))+
  xlab(xlab)+
  ylab(ylab)+
  guides(x =  guide_axis(angle = rotate)) +
  stat_pvalue_manual(stats.df, label = "p.adj.signif",
                      hide.ns = hide.ns,size= stat.size,
                     step.increase = stat.step,tip.length = stat.tip,
                     bracket.nudge.y = stat.backet.nudge)+
  theme(legend.position = legend,
        text = element_text(size = text.size))+
  font("axis.text")+
  font("xylab")+
  scale_color_manual(values = col.lnll)+ 
  guides(color = guide_legend(title = legend.title),
         fill = guide_legend(title = legend.title))
  
}

pcoa.plots <- function(metadata.frame,eigenvalues.df,color,shape,axis_prefix="Axis.",
                       x.axis=1 ,y.axis=2,alpha=0.7,point.size=10,text.size=18, theme.opt=theme_bw(),
                       color.palette=NULL,shape.shapes=c(16,17,15,18),label=NULL){
  ggscatter(metadata.frame, x=paste(axis_prefix,x.axis, sep=""), y=paste(axis_prefix,y.axis, sep=""),color=color,
          shape=shape,
          ggtheme = theme.opt,
          xlab=paste("PCo",x.axis, "(", eigenvalues.df$Eigval[x.axis], " %)", sep = ""),
          ylab=paste("PCo",y.axis, "(", eigenvalues.df$Eigval[y.axis], " %)", sep = ""),
          size=point.size,
          alpha=alpha,
          palette=color.palette,
          label = label,
          repel = TRUE,
          font.label = c("black")
          )+
    scale_shape_manual(values = shape.shapes) +
  # set text size for whole graph. set the background color (white with no lines)
  theme(text = element_text(size = text.size), panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
        legend.position = "right")
}

alpha.diversity <- function(df){
  alpha.div_ <- data.frame(Richness=colSums((df > 0)*1),
                           shannon_index = vegan::diversity(t(df), index = "shannon"),
                           simpsons_index = vegan::diversity(t(df), index = "simpson"),
                           inverse_simpsons_index = 1 / vegan::diversity(t(df), index = "simpson"),
                           pielous_evenness = vegan::diversity(t(df), index = "simpson") / log(colSums((df > 0)*1)))
  return(alpha.div_)
}
```

# Data
```{r}
#load data
virome.votu.table <- read.csv("../Data/normalized_abundance_tables/bulk_virome_normalized_table.csv",row.names = 1)

virome.metadata <- read.csv("../Data/metadata/bulk_metadata.csv",row.names = "SampleID") %>% 
  mutate(SampleID = rownames(.)) %>% 
  mutate(wetup = ifelse(
    Timepoint == "T0",
    "Dry",
    "Wet-Up"
  ))

#MetaT
metat.votu.table <- read.csv("../Data/normalized_abundance_tables/active_votu_abundances.csv",row.names = 1)
metat.metadata <- read.csv("../Data/metadata/metat_metadata.csv",row.names = "SampleID")%>% 
  mutate(SampleID = rownames(.))%>% 
  mutate(wetup = ifelse(
    Timepoint == "T0",
    "Dry",
    "Wet-Up"
  ))

```


# Create distance matrix
```{r}
#### Virome ####
virome.dist <- dist.table(virome.votu.table,"Y", "bray")

virome.meta.d.order <- meta.mod(virome.metadata,virome.dist)

#### MetaT ####
metat.dist <- dist.table(metat.votu.table,"Y", "bray")

metat.meta.d.order <- meta.mod(metat.metadata,metat.dist)

```


Variables for all of the figures
```{r}
text.size=15
point.size = 8
alpha = 0.9

```


# Alpha Diversity

```{r}
#Generate df
virome.alpha.df <- alpha.diversity(virome.votu.table)
virome.m.data <- merge(virome.metadata,virome.alpha.df,by.x="SampleID",by.y="row.names")

metat.alpha.df <- alpha.diversity(metat.votu.table)
metat.m.data <- merge(metat.metadata,metat.alpha.df,by.x="SampleID",by.y="row.names")
```


## plot alpha diversity

```{r}
text.size = 15
point.size = 2.5
jitter.width = 0.75

df <- virome.m.data
x <- "Timepoint"
y <-  "Richness"
A <- as.formula(paste(y, "~", 
                        x))
xlab = "Time point (weeks)"
ylab= "Richness"
rotate=0
legend="none"
fill="Timepoint"

lm.mod <- lm((Richness)~Timepoint,data=df)
shapiro.test(lm.mod$residuals)
aov.mod <- aov(lm.mod)
tukey_hsd.stat <- tukey_hsd(aov.mod) %>% 
  mutate(xmin = case_when(
    grepl("T0",group1) ~ 1,
    grepl("T1",group1) ~ 2,
    grepl("T2",group1) ~ 3,
    TRUE ~ 4
  ),xmax = case_when(
    grepl("T0",group2) ~ 1,
    grepl("T1",group2) ~ 2,
    grepl("T2",group2) ~ 3,
    TRUE ~ 4
  ),
  y.position = max(df$Richness)*1.05)

stats.df=tukey_hsd.stat

virome.richness <- alpha.div.plot(df = df,stats.df = tukey_hsd.stat,x=x,y=y,fill =  fill,color = fill,xlab = xlab,ylab = ylab,legend.title = "Time point (weeks)", 
                                        jitter.size = point.size,
                                        text.size = text.size,
                                  jitter.width = jitter.width)


virome.richness+
  theme(legend.position = "right")

### MetaT

df <- metat.m.data
x <- "Timepoint"
y <-  "Richness"
A <- as.formula(paste(y, "~", 
                        x))
xlab = "Time point (weeks)"
ylab= "Richness"
rotate=0
legend="none"
fill="Timepoint"

lm.mod <- lm((Richness)~Timepoint,data=df)
shapiro.test(lm.mod$residuals)
aov.mod <- aov(lm.mod)
tukey_hsd.stat <- tukey_hsd(aov.mod) %>% 
  mutate(xmin = case_when(
    grepl("T0",group1) ~ 1,
    grepl("T1",group1) ~ 2,
    grepl("T2",group1) ~ 3,
    TRUE ~ 4
  ),xmax = case_when(
    grepl("T0",group2) ~ 1,
    grepl("T1",group2) ~ 2,
    grepl("T2",group2) ~ 3,
    TRUE ~ 4
  ),
  y.position = max(df$Richness)*1.05)

stats.df=tukey_hsd.stat

metat.richness <- alpha.div.plot(df = df,stats.df = tukey_hsd.stat,x=x,y=y,fill =  fill,color = fill,xlab = xlab,ylab = ylab,legend.title = "Time point (weeks)", 
                                        jitter.size = point.size,
                                        text.size = text.size,
                                 jitter.width = jitter.width)


metat.richness+
  theme(legend.position = "right")

```

# Virome and metat upset
```{r}
virome.votu.table.sum <- virome.votu.table %>%
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("Samples") %>% 
  mutate(timepoint = substr(Samples,1,2)
  ) %>% 
  group_by(timepoint) %>% 
  summarise(across(where(is.numeric), sum),.groups = "drop") %>% 
  column_to_rownames("timepoint") %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate(
    across(everything(), ~ if_else(. > 0, 1, .))
  )%>% 
  rownames_to_column(var = "timepoint")

metat.votu.table.sum <- metat.votu.table %>%
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("Samples") %>% 
  mutate(timepoint = substr(Samples,1,2)
  ) %>% 
  group_by(timepoint) %>% 
  summarise(across(where(is.numeric), sum),.groups = "drop") %>% 
  column_to_rownames("timepoint") %>% 
  t() %>% 
  as.data.frame() %>% 
  mutate(
    across(everything(), ~ if_else(. > 0, 1, .))
  )%>% 
  rownames_to_column(var = "timepoint")

font.size=18

virome.upset <- upset(virome.votu.table.sum,names(virome.votu.table.sum),width_ratio=0.2,min_size=85,
                name = "Time Point",
                themes=upset_default_themes(text=element_text(size=font.size)),
                base_annotations=list(
                  'Intersection size'=intersection_size(
                    text_mapping=aes(label=paste0(!!get_size_mode('distinct'),"\n","(",!!upset_text_percentage(digits = 1, sep = ""),")")),
                    text_colors=c(on_bar='black',
                      on_background="black"
                      ),
                    bar_number_threshold=1,
                    text=list(size = text.size*0.35,
                      vjust=-0.1,
                      angle=0
                      )
                    )+
                    ylab('# of vOTUs')+
                    ylim(c(0,7500))+
                    theme(
                    # hide grid lines
                    panel.grid.major=element_blank(),
                    panel.grid.minor=element_blank()
                    )
                  ),
                queries=list(
                  upset_query(set = 'T0',fill = "burlywood4"),
                  upset_query(set = 'T1',fill = "darkblue"),
                  upset_query(set = 'T2',fill = "steelblue2"),
                  upset_query(set = 'T3',fill = "lightblue")
                ),
                matrix=intersection_matrix(
                  geom=geom_point(
                    shape='circle filled',
                    size=3,
                    stroke=0.45
                    )
                  ),
    set_sizes=(
        upset_set_size()
        + theme(axis.text.x=element_text(angle=45))
    )
    )

metat.upset <- upset(metat.votu.table.sum,names(metat.votu.table.sum),width_ratio=0.2,min_size=8,
                name = "Time Point",
                themes=upset_default_themes(text=element_text(size=font.size)),
                base_annotations=list(
                  'Intersection size'=intersection_size(
                    text_mapping=aes(label=paste0(!!get_size_mode('distinct'),"\n","(",!!upset_text_percentage(digits = 1, sep = ""),")")),
                    text_colors=c(on_bar='black',
                      on_background="black"
                      ),
                    bar_number_threshold=1,
                    text=list(size = text.size*0.35,
                      vjust=-0.1,
                      angle=0
                      )
                    )+
                    ylab('# of vOTUs')+
                    ylim(c(0,3500))+
                    theme(
                    # hide grid lines
                    panel.grid.major=element_blank(),
                    panel.grid.minor=element_blank()
                    )
                  ),
                queries=list(
                  upset_query(set = 'T0',fill = "burlywood4"),
                  upset_query(set = 'T1',fill = "darkblue"),
                  upset_query(set = 'T2',fill = "steelblue2"),
                  upset_query(set = 'T3',fill = "lightblue")
                ),
                matrix=intersection_matrix(
                  geom=geom_point(
                    shape='circle filled',
                    size=3,
                    stroke=0.45
                    )
                  ),
    set_sizes=(
        upset_set_size()
        + theme(axis.text.x=element_text(angle=45))
    )
    )

```

#  Bray-Curtis Distance
## Helper function to create ellipse
```{r}
library(dplyr)
library(purrr)

# df must have columns Axis.1 and Axis.2
make_ellipse <- function(df, x_col, y_col, level = 0.95, npoints = 200) {
  coords <- df[, c(x_col, y_col)]
  center <- colMeans(coords)
  S      <- cov(coords)

  # radius from chi-square with df = 2
  r      <- sqrt(qchisq(level, df = 2))

  angles <- seq(0, 2 * pi, length.out = npoints)
  circle <- cbind(cos(angles), sin(angles))

  ellipse <- t(center + r * t(circle %*% chol(S)))
  out     <- as.data.frame(ellipse)
  names(out) <- c(x_col, y_col)   # keep same col names as input
  out
}


```

## Plot the figures
```{r}
point.size = 3.25
####Virome####
print("Virome")
virome.pcoa <- pcoa(as.dist(virome.dist))

# make a dataframe named axes, put pcoa values in there
virome.axes <- as.data.frame(virome.pcoa$vectors)

# Give df extra column with the row names in it 
virome.axes$SampleID <- rownames(virome.axes)

# calculate the eigenvalues for each pcoa axes 
virome.eigval <- round(virome.pcoa$values$Relative_eig * 100, digits = 2)

# Put those eigenvalues in a df so they easy to get to. 
virome.eigval <- data.frame( PC = 1:length(virome.eigval), Eigval = virome.eigval)
#head(eigval) # see top eigenvalues
virome.eigval[[1,2]] # see first axes percentage
virome.eigval[[2,2]] # second axes

#Double check they are in the same order

all(rownames(virome.meta.d.order) == rownames(virome.axes))
all(virome.meta.d.order$SampleID == virome.axes$SampleID)
virome.axes <- merge(virome.meta.d.order, virome.axes, by.x = "SampleID", by.y = "SampleID")

#Create the ellipse
ellipses <- virome.axes %>%
  group_by(Timepoint) %>%
  group_modify(~ make_ellipse(.x,x_col = "Axis.1",y_col="Axis.2", level = 0.95, npoints = 200)) %>%
  ungroup()

virome.pcoa <- pcoa.plots(virome.axes ,virome.eigval,shape = "Phosphorus", color = "Timepoint",point.size = point.size, text.size = text.size,color.palette = col.lnll,alpha = alpha,x.axis = 1,y.axis = 2)+
  guides(
         color = guide_legend(title = "Time point (weeks)")) + 
  geom_path(
    data = ellipses,
    aes(
      x = Axis.1,
      y = Axis.2,
      group    = Timepoint,
      color    = Timepoint,
      linetype = Timepoint
    ),
    alpha = 0.8,
    show.legend = FALSE
  )+
  scale_shape_manual(
    values = shape.lnll,
    labels = c(
      "Phosphorus" = "Wet (+P)",
      "No Phosphorus" = "Wet (-P)",
      "Dry" = "Dry"
    ),
    name = "Soil Treatment"
  )

virome.axes$Timepoint <- as.factor(virome.axes$Timepoint)

set.seed(1990)

adonis2(as.dist(virome.dist)~Timepoint,data=virome.axes, by = "terms")
adonis2(as.dist(virome.dist)~Phosphorus,data=virome.axes, by = "terms")
adonis2(as.dist(virome.dist)~wetup,data=virome.axes, by = "terms")
adonis2(as.dist(virome.dist)~Timepoint*Phosphorus,data=virome.axes, by = "terms")


pairwise.adonis(as.dist(virome.dist),virome.axes$Timepoint)
pairwise.adonis(as.dist(virome.dist),virome.axes$Phosphorus)
pairwise.adonis(as.dist(virome.dist),virome.axes$wetup)

lapply(c("T1", "T2", "T3"),function(x){
  print(x)
  dist_ <- virome.dist[,grepl(x,colnames(virome.dist))]
  dist_ <- dist_[grepl(x,rownames(dist_)),]
  meta.data_ <- virome.axes %>% filter(Timepoint == x)
  print(pairwise.adonis(as.dist(dist_),meta.data_$Phosphorus))
})

print(virome.pcoa)

####MetaT####
print("Metat")
metat.pcoa <- pcoa(as.dist(metat.dist))

# make a dataframe named axes, put pcoa values in there
metat.axes <- as.data.frame(metat.pcoa$vectors)

# Give df extra column with the row names in it 
metat.axes$SampleID <- rownames(metat.axes)

# calculate the eigenvalues for each pcoa axes 
metat.eigval <- round(metat.pcoa$values$Relative_eig * 100, digits = 2)

# Put those eigenvalues in a df so they easy to get to. 
metat.eigval <- data.frame( PC = 1:length(metat.eigval), Eigval = metat.eigval)
#head(eigval) # see top eigenvalues
metat.eigval[[1,2]] # see first axes percentage
metat.eigval[[2,2]] # second axes

#Double check they are in the same order

all(rownames(metat.meta.d.order) == rownames(metat.axes))
all(metat.meta.d.order$SampleID == metat.axes$SampleID)
metat.axes <- merge(metat.meta.d.order, metat.axes, by.x = "SampleID", by.y = "SampleID")

# MetaT Ellipse
metat.ellipses <- metat.axes %>%
  group_by(Phosphorus, Timepoint) %>%
  group_modify(~ make_ellipse(.x, x_col = "Axis.3", y_col = "Axis.1",
                                 level = 0.95, npoints = 200)) %>%
  ungroup()

metat.pcoa <- pcoa.plots(metat.axes ,metat.eigval,shape = "Phosphorus", color = "Timepoint",point.size = point.size, text.size = text.size,color.palette = col.lnll,alpha = alpha,x.axis = 3,y.axis = 1)+
  guides(
         color = guide_legend(title = "Time point (weeks)")) + 
  geom_path(
    data = metat.ellipses,
    aes(
      x        = Axis.3,
      y        = Axis.1,
      group    = interaction(Phosphorus, Timepoint),
      color    = Timepoint,
      linetype = Timepoint
    ),
    alpha       = 0.8,
    show.legend = FALSE
  ) +
  scale_shape_manual(
    values = shape.lnll,
    labels = c(
      "Phosphorus" = "Wet (+P)",
      "No Phosphorus" = "Wet (-P)",
      "Dry" = "Dry"
    ),
    name = "Soil Treatment"
  )

metat.axes$Timepoint <- as.factor(metat.axes$Timepoint)

set.seed(1990)

adonis2(as.dist(metat.dist)~Timepoint,data=metat.axes, by = "terms")
adonis2(as.dist(metat.dist)~Phosphorus,data=metat.axes, by = "terms")
adonis2(as.dist(metat.dist)~wetup,data=metat.axes, by = "terms")
adonis2(as.dist(metat.dist)~Phosphorus*Timepoint,data=metat.axes, by = "terms")


pairwise.adonis(as.dist(metat.dist),metat.axes$Timepoint)
pairwise.adonis(as.dist(metat.dist),metat.axes$Phosphorus)
pairwise.adonis(as.dist(metat.dist),metat.axes$wetup)

# Test phosphorus effect at each time point
dist_ <- metat.dist[,grepl("P",colnames(metat.dist))]
dist_ <- dist_[grepl("P",rownames(dist_)),]
meta.data_ <- metat.axes %>% filter(Phosphorus=="Phosphorus")
pairwise.adonis(as.dist(dist_),meta.data_$Timepoint)

# Test no phosphorus effect at each time point
dist_ <- metat.dist[,!grepl("P|Dry",colnames(metat.dist))]
dist_ <- dist_[!grepl("P|Dry",rownames(dist_)),]
meta.data_ <- metat.axes %>% filter(Phosphorus=="No Phosphorus")
pairwise.adonis(as.dist(dist_),meta.data_$Timepoint)

```

# Make one figure
```{r}

label.size = 18


pcoa.figs <- virome.pcoa +
  ggtitle("Virome")+
  metat.pcoa + 
  ggtitle("Metatranscriptome") +
  plot_annotation(tag_levels = "A") + 
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom",
        plot.tag = element_text(size = label.size, face = "bold"))


richness.fig <- plot_grid(virome.richness, metat.richness,
                      labels = c("C","D"),
                     nrow = 2,
                     label_size = label.size)

upset.figs <- plot_grid(virome.upset,metat.upset,
                      labels = c("E","F"),
                     nrow = 1,
                     label_size = label.size)

top.figs <- plot_grid(pcoa.figs,richness.fig,
                     nrow = 1,
                     rel_widths = c(1,0.5),
                     label_size = label.size)

final.div.tb <- plot_grid(top.figs,upset.figs,
                          nrow = 2,
                          rel_heights = c(1,0.65)
                          )

ggsave(plot=final.div.tb, "../figures/figure2.png",height=10,width=18)
ggsave(plot=final.div.tb, "../figures/figure2.svg",height=10,width=18)
```
