---
title: "figure1"
author: "GG"
date: "2024-10-29"
output: html_document
---

```{r, echo=FALSE,message=FALSE,results='hide',warning=FALSE}
#Load libraries
library(tidyverse)
library(vegan)
library(ape)
library(llnl)
library(ggpubr)
library(pairwiseAdonis)
library(patchwork)
library(rstatix)
library(ComplexUpset)
```

#Load functions
```{r functions, echo=FALSE}
alpha.div.plot <- function(df,stats.df,x,y,fill,color,xlab,ylab,legend.title,
                           text.size,
                           shape,
                            box.alpha = 0,
                            box.line.size = 0.6,
                            box.outliers = FALSE, jitter.width = 0.15,
                            dodge.width = 0.9,jitter.height = 0,
                            jitter.alpha = 0.7,jitter.size = 2,rotate = 0,
                            hide.ns = TRUE, stat.size = 6,
                            stat.step = 0.1, stat.tip = 0,stat.backet.nudge = 0,
                           legend = "none"
                            ){
  ggboxplot(df,x=x,y=y,fill=fill,color=fill,
            outliers = box.outliers,alpha = box.alpha,
            size = box.line.size)+
  geom_jitter(position = position_jitterdodge(jitter.width = jitter.width, dodge.width = dodge.width ,jitter.height = jitter.height),
              alpha = jitter.alpha,
              size = jitter.size,
              aes(color = !!sym(fill),
              shape = !!sym(shape)))+
  #theme_bw()+
  xlab(xlab)+
  ylab(ylab)+
  guides(x =  guide_axis(angle = rotate)) +
  stat_pvalue_manual(stats.df, label = "p.adj.signif",
                      hide.ns = hide.ns,size= stat.size,
                     step.increase = stat.step,tip.length = stat.tip,
                     bracket.nudge.y = stat.backet.nudge)+
  theme(legend.position = legend,
        text = element_text(size = text.size))+
  font("axis.text")+
  font("xylab")+
  scale_color_manual(values = col.lnll)+ 
    scale_shape_manual(values = shape.lnll)+
  guides(color = guide_legend(title = legend.title),
         fill = guide_legend(title = legend.title))
  
}

alpha.div.plot.source <- function(df,stats.df,x,y,fill,color,xlab,ylab,legend.title,shape,
                            box.alpha = 0,
                            box.line.size = 0.6,
                            box.outliers = FALSE, jitter.width = 0.15,
                            dodge.width = 0.9,jitter.height = 0,
                            jitter.alpha = 0.7,jitter.size = 2,rotate = 0,
                            hide.ns = TRUE, stat.size = 6,
                            stat.step = 0.1, stat.tip = 0,stat.backet.nudge = 0,
                           legend = "none"
                            ){
  ggboxplot(df,x=x,y=y,fill=fill,color=fill,
            outliers = box.outliers,alpha = box.alpha,
            size = box.line.size)+
  geom_jitter(position = position_jitterdodge(jitter.width = jitter.width, dodge.width = dodge.width ,jitter.height = jitter.height),
              alpha = jitter.alpha,
              size = jitter.size,
              aes(color = !!sym(fill),
                  shape = !!sym(shape)))+
  #theme_bw()+
  xlab(xlab)+
  ylab(ylab)+
  guides(x =  guide_axis(angle = rotate)) +
  stat_pvalue_manual(stats.df, label = "p.adj.signif",
                      hide.ns = hide.ns,size= stat.size,
                     step.increase = stat.step,tip.length = stat.tip,
                     bracket.nudge.y = stat.backet.nudge)+
  theme(legend.position = legend)+
  font("axis.text")+
  font("xylab")+
  scale_color_manual(values = col.lnll)+ 
  scale_shape_manual(values = shape.lnll)+ 
  guides(color = guide_legend(title = legend.title),
         fill = guide_legend(title = legend.title))
  
}


pcoa.plots <- function(metadata.frame,eigenvalues.df,color,shape,axis_prefix="Axis.",
                       x.axis=1 ,y.axis=2,alpha=0.7,point.size=10,text.size=18, theme.opt=theme_bw(),
                       color.palette=NULL,shape.shapes=c(16,17,15,18),label=NULL){
  ggscatter(metadata.frame, x=paste(axis_prefix,x.axis, sep=""), y=paste(axis_prefix,y.axis, sep=""),color=color,
          shape=shape,
          ggtheme = theme.opt,
          xlab=paste("PCo",x.axis, "(", eigenvalues.df$Eigval[x.axis], " %)", sep = ""),
          ylab=paste("PCo",y.axis, "(", eigenvalues.df$Eigval[y.axis], " %)", sep = ""),
          size=point.size,
          alpha=alpha,
          palette=color.palette,
          label = label,
          repel = TRUE,
          font.label = c("black")
          )+
    scale_shape_manual(values = shape.shapes) +
  # set text size for whole graph. set the background color (white with no lines)
  theme(text = element_text(size = text.size), panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
        legend.position = "right")
}

alpha.diversity <- function(df){
  alpha.div_ <- data.frame(Richness=colSums((df > 0)*1),
                           shannon_index = vegan::diversity(t(df), index = "shannon"),
                           simpsons_index = vegan::diversity(t(df), index = "simpson"),
                           inverse_simpsons_index = 1 / vegan::diversity(t(df), index = "simpson"),
                           pielous_evenness = vegan::diversity(t(df), index = "simpson") / log(colSums((df > 0)*1)))
  return(alpha.div_)
}

#From https://github.com/cmsantosm/WetupViromes/blob/main/General/general_functions.R
tidy_otu <- function(otu) {
  as.data.frame(otu) %>%
    mutate(OTU_ID = row.names(otu)) %>%
    tidyr::gather(key = "SampleID", value = "Count", -OTU_ID)
}

# Helper: run specaccum on a community matrix (rows = samples, cols = OTUs)
specaccum_df <- function(df, trt, perms = 999,seed = 1990) {
  # Keep only OTU columns (drop SampleID/Treatment) and make sure numeric
  comm <- df %>%
    select(-Treatment) %>%
    mutate(across(everything(), ~ as.numeric(.))) %>%
    as.matrix()

  # species accumulation (random order, many permutations)
  set.seed(seed)
  sa <- specaccum(comm, method = "random", permutations = perms)

  # to data frame
  tibble(
    Samples   = sa$sites,
    Richness  = sa$richness,
    SD        = sa$sd,
    Treatment = trt
  )
}
```


```{r}
#load data
#Virome
virome.votu.table <- read.csv("../Data/normalized_abundance_tables/bulk_virome_normalized_table.csv",row.names = 1)

virome.votu.table <- virome.votu.table %>% 
  rownames_to_column("vOTUs") %>% 
  mutate(vOTUs = gsub("\\||/|-","\\.",vOTUs)) %>% 
  column_to_rownames("vOTUs")

virome.metadata <- read.csv("../Data/metadata/bulk_metadata.csv",row.names = "SampleID") %>% 
  mutate(SampleID = rownames(.))

#Active
metat.votu.table <- read.csv("../Data/normalized_abundance_tables/active_votu_abundances.csv",row.names = 1)

metat.metadata <- read.csv("../Data/metadata/metat_metadata.csv",row.names = "SampleID")%>% 
  mutate(SampleID = rownames(.))

```

```{r}
# Number of vOTUs in each data set

n.virome <- nrow(virome.votu.table)

print(paste("Number of vOTUs in the virome:",n.virome))

n.active <- nrow(metat.votu.table)

print(paste("Number of vOTUs in active community:",n.active))
```


#Combine virome and metaT abundance dataframes
```{r}
combined.abundance <-  metat.votu.table %>% 
  rownames_to_column("votus")%>% 
  full_join(virome.votu.table %>% 
  rownames_to_column("votus"),by = join_by(votus)) %>% 
  column_to_rownames("votus") %>% 
  mutate(across(everything(), ~replace_na(.x, 0)))


#Check they merged correctly 

all.equal(
  colSums(virome.votu.table), 
  colSums(combined.abundance[names(combined.abundance) %in% names(virome.votu.table)]),
  tolerance = 1e-8
)

all.equal(
  colSums(metat.votu.table), 
  colSums(combined.abundance[names(combined.abundance) %in% names(metat.votu.table)]),
  tolerance = 1e-8
)

# Combine Metadata
combine.metat.data <- rbind(metat.metadata %>% 
                              mutate(source = "Metatranscriptome"),virome.metadata%>% 
                              mutate(source = "Virome"))

```


Create distance matrix
```{r}
#### Combined ####
combine.dist <- dist.table(combined.abundance,"Y", "bray")
combine.meta.d.order <- meta.mod(combine.metat.data,combine.dist)
```

Variables for all of the figures
```{r}
text.size=18
point.size = 9
alpha = 0.9

```


# Alpha Diversity

```{r}
#Generate df
virome.alpha.df <- alpha.diversity(virome.votu.table) #generate alpha diversity metrics
virome.m.data <- merge(virome.metadata,virome.alpha.df,by.x="SampleID",by.y="row.names") #merge alpha diversity with metadata

metat.alpha.df <- alpha.diversity(metat.votu.table) #generate alpha diversity metrics
metat.m.data <- merge(metat.metadata,metat.alpha.df,by.x="SampleID",by.y="row.names") #merge alpha diversity with metadata
```


# plot alpha diversity

## Alpha diversity metat and virome
```{r}
text.size = 18
point.size = 4.5

#Merge metadata dfs
df_ <- virome.m.data %>%
  mutate(Source = "Virome") %>% 
  bind_rows(metat.m.data%>%
    mutate(Source = "Metatranscriptome")
    ) 
      # mutate(dry.wet = ifelse(
      # Timepoint == "T0",
      # "Dry",
      # "Wet-Up"))

df <- df_
x <- "Source"
y <-  "Richness"
A <- as.formula(paste(y, "~", 
                        x))
xlab = "Virus Source"
ylab= "Richness"
rotate=0
legend="none"
fill="Source"

df %>%
  kruskal_test(Richness~Source)

all.stat <- df %>% 
  dunn_test(Richness~Source) %>% 
  add_xy_position()

virome.metat.richness <- alpha.div.plot(df,all.stat,x,y, shape="Phosphorus",
                                        jitter.width = 0.55,
                                         fill,fill,xlab,ylab,"Treatments",
                                        stat.step = 0,
                                        jitter.size = point.size,
                                        box.line.size = 0.8,
                                        text.size = text.size,
                                        stat.size = 8,
                                        jitter.alpha = 0.5)+ 
  scale_y_continuous(breaks = seq(0, 13500, 2500), limits = c(0, 13000))


virome.metat.richness+
  theme(legend.position = "none")

```

# Virome and metat upset
```{r}
virome.votu.table.sum <- virome.votu.table %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Samples") %>%
  mutate(Treatment = case_when(
    grepl("T0",Samples) ~ "Virome - Dry",
    # grepl("P",Samples) ~ "Virome + P",
    TRUE ~ "Virome - Post-Wet Up"
  )) %>%
  group_by(Treatment) %>%
  summarise(across(where(is.numeric), sum),.groups = "drop") %>%
  column_to_rownames("Treatment") %>%
  t() %>%
  as.data.frame() %>%
  mutate(
    across(everything(), ~ if_else(. > 0, 1, .))
  )%>%
  rownames_to_column(var = "Treatment")

metat.votu.table.sum <- metat.votu.table %>%
   t() %>%
  as.data.frame() %>%
  rownames_to_column("Samples") %>%
  mutate(Treatment = case_when(
    grepl("T0",Samples) ~ "Metatranscriptome - Dry",
    # grepl("P",Samples) ~ "Metatranscriptome + P",
    TRUE ~ "Metatranscriptome - Post-Wet Up"
  )) %>%
  group_by(Treatment) %>%
  summarise(across(where(is.numeric), sum),.groups = "drop") %>%
  column_to_rownames("Treatment") %>%
  t() %>%
  as.data.frame() %>%
  mutate(
    across(everything(), ~ if_else(. > 0, 1, .))
  )%>%
  rownames_to_column(var = "Treatment")

metat.virome.sums <- virome.votu.table.sum %>% 
  full_join(metat.votu.table.sum) %>% 
  column_to_rownames("Treatment") %>% 
  as.data.frame() %>% 
  mutate(across(everything(), ~ replace_na(., 0)))

font.size=16

metat.virome.upset <- upset(metat.virome.sums,names(metat.virome.sums),width_ratio=0.2,min_size=10,
                name = "Time Point",
                themes=upset_default_themes(text=element_text(size=16)),
                base_annotations=list(
                  'Intersection size'=intersection_size(
                    text_mapping=aes(label=paste0(!!get_size_mode('distinct'),"\n","(",!!upset_text_percentage(digits = 1, sep = ""),")")),
                    text_colors=c(on_bar='black',
                      on_background="black"
                      ),
                    bar_number_threshold=1,
                    text=list(size = text.size*0.35,
                      #vjust=-0.1,
                      vjust=-0.1,
                      #hjust=0.2,
                      angle=0
                      )
                    )+
                    ylab('# of vOTUs')+
                    ylim(c(0,10000)) +
                    theme(
                      panel.grid.major = element_blank(),
                      panel.grid.minor = element_blank()
                    )
                  ),
                queries=list(
                  upset_query(set = 'Virome - Dry',fill = "#1D1160"),
                  upset_query(set = 'Virome - Post-Wet Up',fill = "#1D1160"),
                  upset_query(set = 'Metatranscriptome - Dry',fill = "darkgreen"),
                  upset_query(set = 'Metatranscriptome - Post-Wet Up',fill = "darkgreen")
                ),
                matrix=intersection_matrix(
                  geom=geom_point(
                    shape= 'circle filled',
                    size=3,
                    stroke=0.45
                    )
                  ),
    set_sizes=(
        upset_set_size()
        + theme(axis.text.x=element_text(angle=45))
    )
    )

```

# Combined Bray-Curtis Distance

```{r}
####combine####
combine.pcoa <- pcoa(as.dist(combine.dist))

# make a dataframe named axes, put pcoa values in there
combine.axes <- as.data.frame(combine.pcoa$vectors)

# Give df extra column with the rownames in it 
combine.axes$SampleID <- rownames(combine.axes)

# calculate the eigenvalues for each pcoa axes 
combine.eigval <- round(combine.pcoa$values$Relative_eig * 100, digits = 2)

# Put those eigenvalues in a df so they easy to get to. 
combine.eigval <- data.frame( PC = 1:length(combine.eigval), Eigval = combine.eigval)
#head(eigval) # see top eigenvalues
combine.eigval[[1,2]] # see first axes percentage
combine.eigval[[2,2]] # second axes

#Double check they are in the same order

all(rownames(combine.meta.d.order) == rownames(combine.axes))
all(combine.meta.d.order$SampleID == combine.axes$SampleID)
combine.axes <- merge(combine.meta.d.order, combine.axes, by.x = "SampleID", by.y = "SampleID")

text.size = 24
point.size = 9.5
####Combine####
combine.pcoa <- pcoa.plots(combine.axes ,combine.eigval,shape = "Phosphorus", color = "source",point.size = point.size, text.size = text.size,color.palette = col.lnll,alpha = alpha,x.axis = 1,y.axis = 2)+
  guides(shape=guide_legend(title="Treatments"),
         color = guide_legend(title = "Virus Source")) + 
  stat_ellipse(
    data = combine.axes,
    aes(x = Axis.1, y = Axis.2, group = interaction(Phosphorus, source), color = source, linetype = Phosphorus),
    type = "t", 
    level = 0.95, 
    alpha = 0.4,
    show.legend = FALSE
  ) 

combine.axes$Timepoint <- as.factor(combine.axes$Timepoint)

set.seed(1990)
combine.axes$source <- as.factor(combine.axes$source)
adonis2(as.dist(combine.dist)~source,data=combine.axes, by = "terms")
adonis2(as.dist(combine.dist)~Timepoint,data=combine.axes, by = "terms")
adonis2(as.dist(combine.dist)~Phosphorus,data=combine.axes, by = "terms")
adonis2(as.dist(combine.dist)~Phosphorus*Timepoint,data=combine.axes, by = "terms")
adonis2(as.dist(combine.dist)~source*Timepoint,data=combine.axes, by = "terms")


pairwise.adonis(as.dist(combine.dist),combine.axes$Timepoint)
pairwise.adonis(as.dist(combine.dist),combine.axes$Phosphorus)

hull <- combine.axes %>% 
  group_by(Timepoint) %>% 
  slice(chull(Axis.1, Axis.2))

print(combine.pcoa)

```
# Species accumulation curves

```{r}
set.seed(1990)
accum.virome <- t(virome.votu.table) %>% 
  data.frame() %>% 
  rownames_to_column(var="SampleID") %>%
  mutate(Treatment = ifelse(grepl("T0",SampleID),"Dry",
                            ifelse(grepl("P",SampleID),"Phosphorus","No Phosphorus"))) %>% 
  column_to_rownames("SampleID") %>% 
  select(-Treatment) %>% 
  specaccum(., method = "random", permutations = 999)

accum.metat <- t(metat.votu.table) %>% 
  data.frame() %>% 
  rownames_to_column(var="SampleID") %>%
  mutate(Treatment = ifelse(grepl("T0",SampleID),"Dry",
                            ifelse(grepl("P",SampleID),"Phosphorus","No Phosphorus"))) %>% 
  column_to_rownames("SampleID") %>% 
  select(-Treatment) %>% 
  specaccum(., method = "random", permutations = 100)

  
metat.perm.matrix <- accum.metat$perm
metat.perm.tidy <- as_tibble(metat.perm.matrix) %>%
  mutate(Samples = 1:nrow(.)) %>%
  gather(key = "Permutation", value = "Species", -Samples) %>% 
  mutate(Type = "Metatranscriptome")


virome.perm.matrix <- accum.virome$perm
virome.perm.tidy <- as_tibble(virome.perm.matrix) %>%
  mutate(Samples = 1:nrow(.)) %>%
  gather(key = "Permutation", value = "Species", -Samples)%>% 
  mutate(Type = "Virome")


virome.richness <- data.frame(Samples = accum.virome$sites, 
                              Species = accum.virome$richness, 
                             sd = accum.virome$sd) %>% 
  mutate(Type = "Virome")

metat.richness <- data.frame(Samples = accum.metat$sites, 
                             Species = accum.metat$richness, 
                             sd = accum.metat$sd) %>% 
  mutate(Type = "Transcriptionally Active")

# Combine

all.tidy <- rbind(virome.perm.tidy,metat.perm.tidy)

all.richness <- rbind(virome.richness,metat.richness)

collect <- ggline(data=all.richness,x="Samples",y="Species",color="Type",size=1)+
  geom_ribbon(data=all.richness,aes(x=Samples,y=Species,ymin=Species-sd,ymax=Species+sd,fill=Type),alpha=0.2,color=NA)+
  scale_color_manual(values= col.lnll)+
  scale_fill_manual(values= col.lnll)+
  ylab("Cumulative richness\n(# of vOTUs)") +
  xlab("Sampling effort\n(# of samples)")+
  theme(legend.position = "none")+
  scale_y_continuous(breaks = seq(0, 17500, 2500))
```

# Make one figure
```{r}
label.size = 26
library(cowplot)

pcoa.legend <- combine.pcoa +
  theme(legend.position = "right",
        legend.direction = "horizontal",   # forces horizontal orientation
        legend.background = element_blank(),        # Removes fill inside the legend
    legend.box.background = element_blank(),    # Removes border around the legend
    panel.background = element_blank() ,
    legend.box = "horizontal") +
  scale_color_manual(
    values = col.lnll,
    labels = c("Metatranscriptome", "Virome")
  )

pcoa.legend <- get_legend(pcoa.legend)

pcoa.figs <- plot_grid(combine.pcoa+
               theme(legend.position="none") )

left.fig <- plot_grid(pcoa.figs,
                      labels = c("A"),
                     nrow = 1,
                     #rel_widths = c(1,0.1),
                     label_size = label.size)

bottom.right <- plot_grid(virome.metat.richness,collect,
                      labels = c("C","D"),
                     nrow = 1,
                     rel_widths = c(1,1),
                     label_size = label.size)

right.figs <- plot_grid(metat.virome.upset,bottom.right,labels = c("B",NULL,"C"),
                     nrow = 2,
                     #rel_widths = c(1,0.7,0.1),
                     label_size = label.size)

# final.div.tb <- plot_grid(left.fig,right.figs,pcoa.legend,ncol = 3,rel_widths = c(1,0.75,0.2))
final.div <- plot_grid(left.fig,right.figs,ncol = 2,rel_widths = c(1,0.85))

final.div.tb <- plot_grid(final.div,pcoa.legend,nrow = 2,rel_heights = c(1,0.1))

ggsave(plot=final.div.tb, "../figures/figure1.png",height=10.5,width=27)
# had to edit post generation - saved as a svg to do so
ggsave(plot=final.div.tb, "../figures/figure1.svg",height=10.5,width=27)
```
